### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by MarcoAurelioAntonio** [taldr27/catalog#21]
## Good day! ⛅
 This issue is created to prepare a Kanban board with a GitHub project for _Ruby Capstone_.

### Changes made 🧰 
- Create and set up a new _repo_.
- Create a new _kanban board_.
- Create cards for every task and assign a user.

Kanban board: [Ruby Capstone](https://github.com/users/taldr27/projects/10/views/1)

### Role assignment ✅ 
- Team member # 1 @taldr27 
- Team member # 2 @MarcoAurelioAntonio 
- Team member # 3 @Gleennkar 

Happy coding! 👏

**Comment by Davidosky007** [comment]
Hi @MarcoAurelioAntonio @Gleennkar @taldr27, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All information provided 👍 
* Link to project works 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
